### ISSUE TITLE
Como usa a lib?

### ISSUE THREAD

**Issue by Renan-Olovics** [osmirmariano/ofx-convert#2]
Consegue criar um exemplo melhor de como usar a lib?

**Comment by osmirmariano** [comment]
Ola Renan, consigo sim.

Aqui no projeto tem exemplo de como deve ser utilizado
https://github.com/osmirmariano/ofx-convert


![image](https://user-images.githubusercontent.com/11689638/148292693-4c9706f8-e08c-4618-a178-11b75443175c.png)
